name: shared matrix
on:
  push:
  workflow_dispatch:

jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Define Color
        env:
          os: ${{ matrix.os }}
          version: ${{ matrix.version }}
        run: |
          echo "$os" > os
          echo "$version" > version
